// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneweekNutrition.Data;

#nullable disable

namespace OneweekNutrition.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230227162111_manytomany")]
    partial class manytomany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OneweekNutrition.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Calories")
                        .HasColumnType("float");

                    b.Property<float>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<string>("ImgPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Protein")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Component");
                });

            modelBuilder.Entity("OneweekNutrition.Models.RecipComponent", b =>
                {
                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("RecipId")
                        .HasColumnType("int");

                    b.HasKey("CompId", "RecipId");

                    b.HasIndex("RecipId");

                    b.ToTable("RecipComponent");
                });

            modelBuilder.Entity("OneweekNutrition.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<int?>("Carbohydrates")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Protein")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("OneweekNutrition.Models.RecipComponent", b =>
                {
                    b.HasOne("OneweekNutrition.Models.Component", "Component")
                        .WithMany("Recips")
                        .HasForeignKey("CompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneweekNutrition.Models.Recipe", "Recipe")
                        .WithMany("Components")
                        .HasForeignKey("RecipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("OneweekNutrition.Models.Component", b =>
                {
                    b.Navigation("Recips");
                });

            modelBuilder.Entity("OneweekNutrition.Models.Recipe", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
